name: Lint Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Python Linter
        run: |
          # Find all Python files and run flake8
          echo "Running flake8 on Python files..."
          find . -name "*.py" -exec flake8 {} +
          echo "Linted all the Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install --global jshint

      - name: Run JavaScript Linter
        run: |
          # Find all JavaScript files in the server/database directory and run JSHint
          echo "Running JSHint on JavaScript files..."
          find ./server/database -name "*.js" -exec jshint {} +
          echo "Linted all the JavaScript files successfully"
